- name: Install mariadb
  yum: 
    name:
      - mariadb
      - mariadb-server

- name: Start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Create databases
  shell: mysql -e "CREATE DATABASE IF NOT EXISTS {{ db_name }};"

- name: Check user
  shell: mysql -e "select 1 from mysql.user where user = '{{ db_user }}';" | grep 1
  register: check_user
  ignore_errors: yes

- name: Create user
  shell: mysql -e "CREATE USER {{ db_user }}@localhost IDENTIFIED BY '{{ db_password }}';"
  when: check_user.rc != 0

- name: Grant Access
  shell: mysql -e "GRANT ALL PRIVILEGES ON {{ db_name }}.* TO {{ db_user }}@localhost IDENTIFIED BY '{{ db_password }}';"

- name: Flush
  shell: mysql -e "FLUSH PRIVILEGES;"

