- hosts: all
  tasks:
  - name: install packages
    yum:
      name: httpd
      state: latest
    register: hello
    ignore_errors: yes

  - name: Start apache
    service:
      name: httpd
      state: started 
    register: kaizen
    ignore_errors: yes

  - debug: msg={{ hello }}
  - debug: msg={{ kaizen }}